import{a as L,S,i as q}from"./assets/vendor-u8rapaCG.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const $="46206766-d6f3ed66bf4f64987a1edf465",v="https://pixabay.com/api/";async function P(e,t=1,a=15){const s=Number(t),r=Number(a),o=`${v}?key=${$}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${s}&per_page=${r}`;try{const n=await L.get(o);return console.log("Response data:",n.data),n.data}catch(n){throw console.error("Fetching images failed:",n),n}}function N(e){return`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" width="360" loading="lazy" data-caption="${e.tags}" />
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </a>
    `}function C(e){const t=document.querySelector(".gallery"),a=e.map(N).join("");t.insertAdjacentHTML("beforeend",a),b.refresh()}function O(){document.querySelector(".gallery").innerHTML=""}let f=1;const p=15,g=document.querySelector("#search-form"),h=g.querySelector("input"),m=document.querySelector(".loader"),d=document.querySelector(".load-btn");document.querySelector(".gallery");let b=new S(".gallery a",{captions:!0,captionsData:"data-caption",captionDelay:250}),i="",l=!1,c=!1;g.addEventListener("submit",E);d.addEventListener("click",I);async function E(e){if(e.preventDefault(),i=h.value.trim(),!i){u("warning","Please enter a search query!");return}f=1,O(),l=!1,y(!0),d.style.display="none",await w(i)}async function w(e){if(!c){c=!0;try{const t=await P(e,f,p);if(y(!1),t.hits.length===0){u("info","Sorry, no images were found for your search query.");return}C(t.hits),b.refresh(),t.totalHits>f*p?(d.style.display="block",l=!1):(d.style.display="none",l||(u("info","We're sorry, but you've reached the end of search results."),l=!0)),R(),h.value=""}catch(t){y(!1),u("error","Something went wrong. Please try again later."),console.error(t)}finally{c=!1}}}function I(){c||(f+=1,w(i))}function y(e){m?m.style.display=e?"flex":"none":console.error("Loader element not found in the DOM.")}function u(e,t){q[e]({title:e.charAt(0).toUpperCase()+e.slice(1),message:t})}function R(){const e=document.querySelector(".gallery").firstElementChild;if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
